from typing import Any, Dict, List, Optional, Tuple

from remem.agent import AgentConfig
from remem.agent.strategies.tool_strategy import RetrievalResult, ToolStrategy


class FlexibleToolsStrategy(ToolStrategy):
    """Strategy using flexible tool selection."""

    def __init__(
        self,
        agent_config: AgentConfig,
        tool_selector,
        node_utils,
        agent_logger,
        answer_generator,
        node_chunks_dict,
        remem,
        logger,
    ):
        super().__init__(agent_config)
        self.tool_selector = tool_selector
        self.node_utils = node_utils
        self.agent_logger = agent_logger
        self.answer_generator = answer_generator
        self.node_chunks_dict = node_chunks_dict
        self.remem = remem
        self.logger = logger

    def retrieve(
        self,
        query: str,
        max_results: int = 10,
        return_chunk: Optional[str] = None,
        gold_answer: Optional[str] = None,
        question_metadata: Optional[Dict[str, Any]] = None,
    ) -> RetrievalResult:
        """Execute flexible tool selection retrieval."""

        max_steps = self.agent_config.max_steps
        self.agent_logger.log_session_start(query, max_steps, gold_answer)

        from remem.agent import AgentState

        state = AgentState(query=query, max_steps=max_steps, question_metadata=question_metadata)

        # Main reasoning loop
        while state.current_step < state.max_steps:
            self.agent_logger.log_step_start(state.current_step + 1, state.max_steps)

            should_continue = self._perform_reasoning_step(state, max_results)
            state.current_step += 1

            if not should_continue:
                self.agent_logger.log_stop_condition("Tool indicated stopping graph search")
                break

        # Generate final answer if not already generated
        if not state.final_answer_generated:
            state.final_answer = self._generate_final_answer(state)

        return self._format_result(state, return_chunk)

    def _perform_reasoning_step(self, state, max_results: int) -> bool:
        """Perform one reasoning step using tool selector."""

        if not self.tool_selector:
            self.logger.warning("No tool selector available")
            return False

        try:
            from remem.agent.tools import ToolContext

            context = ToolContext(
                query=state.query,
                visited_nodes=state.visited_nodes,
                reasoning_step=state.current_step,
                max_steps=state.max_steps,
                available_entries=self.node_utils.get_available_entries(self.remem, self.node_chunks_dict),
                content_map=self.node_utils.get_content_map_for_nodes(state.visited_nodes, self.node_chunks_dict),
                previous_steps=self.agent_logger.session_logs.get("llm_interactions", []),
                question_metadata=getattr(state, "question_metadata", None),
            )

            tool_result = self.tool_selector.select_and_execute_tool(context, max_results=max_results)

            # Handle OUTPUT_ANSWER tool
            from remem.agent.tools import ToolType

            if tool_result.tool_type == ToolType.OUTPUT_ANSWER:
                return self._handle_output_answer_tool(state, tool_result, context)

            # Handle other tools
            return self._handle_regular_tool(state, tool_result, context)

        except Exception as e:
            self.logger.error(f"Error in reasoning step: {e}")
            return False

    def _handle_output_answer_tool(self, state, tool_result, context) -> bool:
        """Handle OUTPUT_ANSWER tool selection."""
        state.final_answer_generated = True

        if "Generated final answer: " in tool_result.observation:
            state.final_answer = tool_result.observation.replace("Generated final answer: ", "")
        else:
            state.final_answer = tool_result.observation

        state.reasoning_chain.append("Tool: Final answer generated by tool")

        # Log this step
        empty_passages = []
        self.agent_logger.log_step(state.current_step + 1, tool_result, empty_passages, context)

        return False  # Stop the reasoning loop

    def _handle_regular_tool(self, state, tool_result, context) -> bool:
        """Handle regular tool selection (not OUTPUT_ANSWER)."""
        # Update visited nodes
        state.visited_nodes.update(tool_result.nodes_found)
        state.current_focus_nodes = tool_result.nodes_found

        # Collect content from found nodes
        if hasattr(tool_result, "node_contents") and tool_result.node_contents:
            new_passages = self._create_passages_from_tool_result(tool_result, state.current_step + 1)
        else:
            new_passages = self.node_utils.collect_node_content_with_scores(
                tool_result.nodes_found, tool_result.scores, state.current_step + 1, self.node_chunks_dict, self.remem
            )

        state.retrieved_passages.extend(new_passages)
        self.agent_logger.log_step(state.current_step + 1, tool_result, new_passages, context)
        state.reasoning_chain.append(f"Tool: {tool_result.observation}")

        # Decide whether to continue
        if len(tool_result.nodes_found) == 0:
            self.logger.info("No nodes found in this step. Continuing to next step.")
            return True

        return tool_result.should_continue

    def _create_passages_from_tool_result(self, tool_result, step: int):
        """Create passages from tool result."""
        passages = []
        for node_key, score, content in zip(tool_result.nodes_found, tool_result.scores, tool_result.node_contents):
            node_type = self.node_utils.get_node_type(node_key, self.remem)
            passages.append(
                {
                    "node_name": node_key,
                    "content": content,
                    "embedding_score": score,
                    "step": step,
                    "node_type": node_type,
                }
            )
        return passages

    def _generate_final_answer(self, state):
        """Generate final answer using shared answer generator."""
        content_map = self.node_utils.get_content_map_for_nodes(state.visited_nodes, self.node_chunks_dict)

        return self.answer_generator.generate_answer(
            query=state.query,
            visited_nodes=state.visited_nodes,
            reasoning_step=state.current_step,
            previous_steps=self.agent_logger.session_logs.get("llm_interactions", []),
            question_metadata=state.question_metadata,
            interaction_type="final_answer_generation",
            remem_instance=self.remem,
        )

    def _format_result(self, state, return_chunk: Optional[str]) -> RetrievalResult:
        """Format the final result."""
        chunk_ids, chunk_scores = self._format_agent_results(state, return_chunk)

        logs = {
            "agent_observation": state.reasoning_chain,
            "agent_answer": state.final_answer,
            "agent_chunks": [p["content"] for p in state.retrieved_passages if p.get("content")],
            "agent_session_logs": self.agent_logger._get_session_logs(),
        }

        return RetrievalResult(
            chunk_ids=chunk_ids, chunk_scores=chunk_scores, logs=logs, final_answer=state.final_answer
        )

    def _format_agent_results(self, state, return_chunk: Optional[str] = None) -> Tuple[List[str], List[float]]:
        """Format agent results to match traditional PPR output format."""
        if not state.retrieved_passages:
            return [], []

        # Filter and aggregate passages
        chunk_id_to_max_score = {}
        for passage in state.retrieved_passages:
            node_name = passage.get("node_name")
            if not node_name:
                continue

            node_type = self.node_utils.get_node_type(node_name, self.remem)

            # Filter by return_chunk type
            if return_chunk == "verbatim" and node_type != "verbatim":
                continue
            elif return_chunk == "gists" and node_type != "gists":
                continue

            embedding_score = passage.get("embedding_score", 0.0)
            chunk_id_to_max_score[node_name] = max(chunk_id_to_max_score.get(node_name, 0.0), embedding_score)

        if not chunk_id_to_max_score:
            return [], []

        # Sort by score descending
        sorted_items = sorted(chunk_id_to_max_score.items(), key=lambda x: x[1], reverse=True)
        return [item[0] for item in sorted_items], [item[1] for item in sorted_items]
